#!/bin/bash

FROM alpine:latest

LABEL maintainer="notarobot" \
  ogrydziak.net.release-date="2020-08-16"

RUN apk update && \
  apk upgrade && \
  apk add bind

EXPOSE 80/tcp
EXPOSE 80/udp

ENTRYPOINT ["named", "-g", "-c"]
CMD ["/etc/named.conf"]
