#!/bin/bash

FROM alpine:latest

LABEL maintainer="notarobot" \
  ogrydziak.net.release-date="2020-12-14"

RUN apk update && \
  apk upgrade && \
  apk add bind

COPY ./config /app

EXPOSE 53/tcp
EXPOSE 53/udp

ENTRYPOINT ["named", "-g", "-c"]
CMD ["/app/named.conf"]
