version: "3.9"
services:
  ns1:
    container_name: ns1
    hostname: ns1
    build:
      context: .
    volumes:
      - $LOG_DIR:/app/log
    ports:
      - $SRV_IP1:53:53
      - $SRV_IP1:53:53/udp
    deploy:
      resources:
        limits:
          memory: 2g
  ns2:
    container_name: ns2
    hostname: ns2
    build:
      context: .
    volumes:
      - $LOG_DIR:/app/log
    ports:
      - $SRV_IP2:53:53
      - $SRV_IP2:53:53/udp
      - $SRV_IPV6_2:53:53
      - $SRV_IPV6_2:53:53/udp
    deploy:
      resources:
        limits:
          memory: 2g