#!/bin/bash

FROM docker.io/library/alpine:latest

LABEL maintainer="notarobot" \
  ogrydziak.net.release-date="2020-03-14"

RUN apk update && \
  apk upgrade && \
  apk add bind

COPY ./app /app

EXPOSE 53/tcp
EXPOSE 53/udp

ENTRYPOINT ["named", "-f", "-c"]
CMD ["/app/named.conf"]

#-g #Run the server in the foreground and force all logging to stderr
#-c #Use config-file as the configuration file instead of the default, /etc/named.conf
#https://linux.die.net/man/8/named
