#!/bin/bash

FROM docker.io/library/ubuntu:latest

LABEL maintainer="notarobot" \
  org.label-schema.name="Bind9 DNS Server" \
  org.label-schema.name="OG Networks" \
  org.label-schema.build-date="2020-03-14" \
  org.label-schema.description="Custom DNS server using Bind9 on Alpine Linux" \
  org.label-schema.url="https://github.com/notarobot767/dns-bind9" \
  org.label-schema.vcs-ref="github.com:notarobot767/dns-bind9.git" \
  org.label-schema.cmd="docker run -d -p 53:53 -p 53:53/udp -e TZ='America/New_York' bind9"

ENV TZ=America/New_York
#set timezone variable
#https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

RUN export DEBIAN_FRONTEND=noninteractive && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
  apt-get update -y && apt-get upgrade -y && apt-get install -y tzdata && \
  dpkg-reconfigure --frontend noninteractive tzdata && \
  #update, upgrade, set timezone
  \
  apt-get install -y bind9 && \
  #install bind package
  apt-get clean

COPY ./app /app
#config will live locally on image

EXPOSE 53/tcp
EXPOSE 53/udp
#dns uses both tcp and udp port 53

ENTRYPOINT ["named", "-f", "-4", "-c"]
CMD ["/app/named.conf"]
#CMD would allow user to specify alternative config for container instance

#-g #switch to -g to troubleshoot and see output to console when in interactive mode
#-f #Run the server in the foreground. Necessary when running as docker instance
#-c #Use config-file as the configuration file instead of the default, /etc/named.conf
#https://linux.die.net/man/8/named
